DEFAULT_MAPPING = {
    "Tên quảng cáo": "Ad Name",
    "Tên chiến dịch / bài ads": "Ad Name",
    "Nội dung": "Body",
    "Facebook Post URL": "Permalink",
    "Link bài viết": "Permalink",
    "Story ID": "Story ID",
    "ID Story": "Story ID",
    "Video ID": "Video ID",
    "ID Video": "Video ID",
    "Link URL": "Link",
    "Link đích": "Link",
    "CTA": "Call to Action",
    "Nút CTA": "Call to Action",
    "Tiêu đề link": "Title",
    "Mô tả link": "Link Description",
    "Creative Type": "Creative Type",
    "Loại bài quảng cáo": "Creative Type",
    "Campaign Name": "Campaign Name",
    "Tên chiến dịch": "Campaign Name",
    "Mục tiêu chiến dịch": "Campaign Objective",
    "Ad Set Name": "Ad Set Name",
    "Tên nhóm QC": "Ad Set Name",
    "Lifetime Budget": "Ad Set Lifetime Budget",
    "Ngân sách mẫu": "Ad Set Lifetime Budget",
    "Ngân sách trọn đời": "Ad Set Lifetime Budget",
    "Ngân sách/ngày": "Ad Set Daily Budget",
    "Bid Amount": "Bid Amount",
    "Giá thầu nhập tay": "Bid Amount",
    "Giới hạn giá thầu": "Bid Amount",
    "Chiến lược giá thầu": "Ad Set Bid Strategy",
    "Vị trí chuyển đổi": "Destination Type",
    "Mục tiêu tối ưu": "Optimization Goal",
    "Tập dữ liệu": "Optimized Conversion Tracking Pixels",
    "Billing Event": "Billing Event",
    "Tính phí theo": "Billing Event",
    "Custom Audiences": "Custom Audiences",
    "Đối tượng tuỳ chỉnh": "Custom Audiences",
    "Vị trí địa lý": "Cities",
    "Tuổi min": "Age Min",
    "Tuổi max": "Age Max",
    "Giới tính": "Gender",
    "Ngôn ngữ": "Locales",
    "Thiết bị": "Device Platforms",
    "Nền tảng quảng cáo": "Publisher Platforms",
    "Vị trí Facebook": "Facebook Positions",
    "Vị trí Messenger": "Messenger Positions",
    "Advantage Audience": "Advantage Audience",
    "Mở rộng tệp": "Advantage Audience",
    "Targeting Relaxation": "Targeting Relaxation",
    "Mở rộng nhắm chọn": "Targeting Relaxation",
    "Kiểm soát tần suất": "Frequency Control",
}

SAFE_TEMPLATE_OVERRIDE_FIELDS = {
    "Tên quảng cáo",
    "Tên chiến dịch / bài ads",
    "Nội dung",
    "Facebook Post URL",
    "Link bài viết",
    "Story ID",
    "ID Story",
    "Video ID",
    "ID Video",
    "CTA",
    "Nút CTA",
    "Tiêu đề link",
    "Mô tả link",
    "Creative Type",
    "Loại bài quảng cáo",
    "Campaign Name",
    "Tên chiến dịch",
    "Mục tiêu chiến dịch",
}

VALUE_ALIASES = {
    "Vị trí chuyển đổi": {
        "Mức độ nhận biết": "ON_AD",
        "Đích đến của tin nhắn": "MESSENGER",
        "Tin nhắn": "MESSENGER",
        "Messenger": "MESSENGER",
        "Bài viết": "ON_POST",
        "Video": "ON_VIDEO",
        "Trên quảng cáo của bạn": "ON_POST",
        "Trang web": "WEBSITE",
        "Trang web và ứng dụng": "WEBSITE, APP",
        "Trang web và tại cửa hàng": "WEBSITE, STORE",
        "Trang web, ứng dụng và tại cửa hàng thực": "WEBSITE, APP, STORE",
        "Trang web và mẫu phản hồi tức thì": "WEBSITE, ON_AD",
        "Trang web và cuộc gọi": "WEBSITE, PHONE_CALL",
        "Mẫu phản hồi tức thì và Messenger": "ON_AD, MESSENGER",
        "Mẫu phản hồi tức thì": "ON_AD",
        "Cuộc gọi": "PHONE_CALL",
        "Instagram hoặc Facebook": "FACEBOOK_PAGE",
        "Instagram": "INSTAGRAM_DIRECT",
        "WhatsApp": "WHATSAPP",
        "Ứng dụng": "APP",
    },
    "Mục tiêu chiến dịch": {
        "Mức độ nhận biết": "Outcome Awareness",
        "Awareness": "Outcome Awareness",
        "Lưu lượng truy cập": "Outcome Traffic",
        "Traffic": "Outcome Traffic",
        "Lượt tương tác": "Outcome Engagement",
        "Engagement": "Outcome Engagement",
        "Khách hàng tiềm năng": "Outcome Leads",
        "Leads": "Outcome Leads",
        "Doanh số": "Outcome Sales",
        "Sales": "Outcome Sales",
    },
    "Chiến lược giá thầu": {
        "Giới hạn giá thầu": "Bid cap",
        "Bid cap": "Bid cap",
        "Cost per result goal": "Cost per result goal",
    },
    "Mục tiêu tối ưu": {
        "Tin nhắn": "CONVERSATIONS",
        "Cuộc trò chuyện": "CONVERSATIONS",
        "Tối đa hóa số cuộc trò chuyện": "CONVERSATIONS",
        "Lượt xem video": "THRUPLAY",
        "Tối đa hóa số lượt xem ThruPlay": "THRUPLAY",
        "Tối đa hóa số lượt phát video liên tục trong tối thiểu 2 giây": "TWO_SECOND_CONTINUOUS_VIDEO_VIEWS",
        "Tương tác bài viết": "POST_ENGAGEMENT",
        "Tối đa hóa lượt tương tác với bài viết": "POST_ENGAGEMENT",
        "Tối đa hóa số lượt phản hồi sự kiện": "EVENT_RESPONSES",
        "Tăng tối đa lượt đặt lời nhắc": "REMINDERS",
        "Tối đa hóa số người tiếp cận quảng cáo": "REACH",
        "Tối đa hóa phạm vi tiếp cận quảng cáo": "REACH",
        "Tối đa hóa số người tiếp cận hằng ngày": "REACH",
        "Tối đa hóa số lượt hiển thị": "IMPRESSIONS",
        "Tối đa hóa độ cải thiện khả năng nhớ đến quảng cáo": "AD_RECALL_LIFT",
        "Tối đa hóa mức tăng khả năng nhớ đến quảng cáo": "AD_RECALL_LIFT",
        "Tối đa hóa số khách hàng tiềm năng": "LEAD_GENERATION",
        "Tăng tối đa số khách hàng tiềm năng": "LEAD_GENERATION",
        "Tăng tối đa số khách hàng tiềm năng đủ điều kiện": "QUALITY_LEAD",
        "Tối đa hóa số khách hàng tiềm năng qua tin nhắn": "LEAD_GENERATION",
        "Tối đa hóa số lượt mua qua tin nhắn": "PURCHASE",
        "Tối đa hóa số lượt mua": "PURCHASE",
        "Tối đa hóa giá trị chuyển đổi": "VALUE",
        "Tối đa hóa giá trị của lượt chuyển đổi": "VALUE",
        "Tối đa hóa số lượt click vào liên kết": "LINK_CLICKS",
        "Tối đa hóa số cuộc gọi": "QUALITY_CALL",
        "Tối đa hóa số lượt chuyển đổi": "OFFSITE_CONVERSIONS",
        "Tối đa hóa số lượt xem trang đích": "LANDING_PAGE_VIEWS",
        "Tối đa hóa lượt tương tác với ứng dụng": "APP_EVENTS",
        "Tối đa hóa số lượt truy cập Trang Facebook": "PAGE_VISITS",
        "Tối đa hóa số lượt thích Trang": "PAGE_LIKES",
    },
    "Giới tính": {
        "Nữ": "Women",
        "Nam": "Men",
        "Tất cả": "All",
    },
    "Ngôn ngữ": {
        "Tiếng Việt": "Vietnamese",
    },
    "Thiết bị": {
        "Di động": "mobile",
        "Máy tính": "desktop",
        "Tất cả": "mobile, desktop",
    },
    "Nền tảng quảng cáo": {
        "Facebook + Messenger": "facebook, messenger",
        "Facebook": "facebook",
        "Facebook + Instagram": "facebook, instagram",
    },
    "Advantage Audience": {
        "Tắt": "0",
        "Bật": "1",
    },
    "Mở rộng tệp": {
        "Tắt": "0",
        "Bật": "1",
    },
    "Kiểm soát tần suất": {
        "Giới hạn 2 lần / 7 ngày": '[{"event":"IMPRESSIONS","interval_days":7,"max_frequency":2}]',
        "2 lần / 7 ngày": '[{"event":"IMPRESSIONS","interval_days":7,"max_frequency":2}]',
    },
}
