const state={catalog:null,flows:[],campaign:null,location:null,adset:null,preview:null,previewPayload:null,editingFlowId:null,selectedLinks:[],knownLinks:[],creativePreviews:{},creativePreviewTimer:null,creativePreviewRequest:0,metaCurrency:'TKQC',candidates:[],appView:'planner',editingPresetCode:null,presets:[],reviews:[],selectedReview:null,reviewFilter:'ALL',auth:{authenticated:false,role:'content',csrf_token:null}};
const $=id=>document.getElementById(id);
const LOCAL_PLAN_KEY='khai_hoan_ads_plan_v1';
const els={links:$('linksInput'),linkSelection:$('linkSelectionList'),selectedLinkCount:$('selectedLinkCount'),adName:$('adNameInput'),campaigns:$('campaignList'),locations:$('locationList'),adsets:$('adsetList'),selection:$('selectionStage'),setup:$('setupStage'),path:$('selectedPath'),changeSelection:$('changeSelection'),audience:$('audienceSelect'),dataset:$('datasetSelect'),datasetHint:$('datasetHint'),budget:$('budgetSelect'),placement:$('placementSelect'),budgetType:$('budgetType'),budgetAmount:$('budgetAmount'),budgetCurrency:$('budgetCurrency'),startTime:$('startTime'),hasEndTime:$('hasEndTime'),endTimeField:$('endTimeField'),endTime:$('endTime'),flows:$('flowList'),articles:$('articleList'),summary:$('summaryText'),readiness:$('readiness'),actionSummary:$('actionSummary'),actionHint:$('actionHint'),previewButton:$('previewButton'),createButton:$('createDraftsButton')};

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function links(){return [...new Set(els.links.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];}
function selectedLinks(){const current=new Set(links());return state.selectedLinks.filter(link=>current.has(link));}
function syncLinkSelection(){const current=links(),currentSet=new Set(current),previous=new Set(state.knownLinks),selected=new Set(state.selectedLinks.filter(link=>currentSet.has(link)));current.forEach(link=>{if(!previous.has(link))selected.add(link);});state.flows=state.flows.map(flow=>{const assigned=Array.isArray(flow.link_urls)?flow.link_urls:state.knownLinks;return{...flow,link_urls:assigned.filter(link=>currentSet.has(link))};});state.knownLinks=current;state.selectedLinks=current.filter(link=>selected.has(link));}
function isFacebookLink(link){try{const host=new URL(link).hostname.toLowerCase();return host==='facebook.com'||host.endsWith('.facebook.com')||host==='fb.watch'||host.endsWith('.fb.watch');}catch(_error){return false;}}
function byCode(items,code){return items.find(item=>item.code===code);}
function optionList(select,items,emptyLabel){select.innerHTML=`<option value="">${escapeHtml(emptyLabel)}</option>`+items.map(x=>`<option value="${escapeHtml(x.code)}">${escapeHtml(x.name)}</option>`).join('');}
function defaultLocalDateTime(){const date=new Date();date.setSeconds(0,0);date.setMinutes(Math.ceil(date.getMinutes()/5)*5);const pad=value=>String(value).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function applyBudgetPreset(){const preset=byCode(state.catalog.budgets,els.budget.value);if(!preset)return;const values=preset.notionValues||{};const lifetime=values['Loại ngân sách']==='Lifetime'||Number(values['Ngân sách trọn đời'])>0;els.budgetType.value=lifetime?'Ngân sách trọn đời':'Ngân sách/ngày';const amount=lifetime?values['Ngân sách trọn đời']:values['Ngân sách/ngày'];if(amount!==undefined&&amount!==null&&amount!=='')els.budgetAmount.value=amount;}
function toggleEndTime(){const required=els.budgetType.value==='Ngân sách trọn đời';if(required)els.hasEndTime.checked=true;els.hasEndTime.disabled=required;els.endTimeField.classList.toggle('hidden',!els.hasEndTime.checked);if(!els.hasEndTime.checked)els.endTime.value='';}
function budgetSummary(flow){const custom=flow.custom_budget_values||{};const lifetime=custom['Ngân sách trọn đời']!==undefined;const amount=lifetime?custom['Ngân sách trọn đời']:custom['Ngân sách/ngày'];if(amount!==undefined)return `${amount} ${state.metaCurrency} · ${lifetime?'Trọn đời':'Mỗi ngày'}`;return byCode(state.catalog.budgets,flow.budget_code)?.name||'Chưa chọn ngân sách';}
function scheduleSummary(flow){const format=value=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Không giới hạn';return `${format(flow.start_time)} → ${format(flow.end_time)}`;}
function showToast(message,error=false){const toast=$('toast');toast.textContent=message;toast.className=`toast${error?' error':''}`;setTimeout(()=>toast.classList.add('hidden'),3500);}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.auth.csrf_token&&options.method&&options.method!=='GET')headers['X-CSRF-Token']=state.auth.csrf_token;const response=await fetch(path,{...options,headers,credentials:'same-origin'});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Máy chủ không phản hồi');return data;}
function saveLocalPlan(){try{localStorage.setItem(LOCAL_PLAN_KEY,JSON.stringify({version:2,links:els.links.value,selectedLinks:state.selectedLinks,adName:els.adName.value,flows:state.flows}));}catch(_error){}}
function restoreLocalPlan(){try{const saved=JSON.parse(localStorage.getItem(LOCAL_PLAN_KEY)||'null');if(!saved||![1,2].includes(saved.version))return false;const campaigns=new Set(state.catalog.campaigns.map(x=>x.code));const adsets=new Map(state.catalog.adsets.map(x=>[x.code,x]));els.links.value=String(saved.links||'');const current=links(),currentSet=new Set(current);state.knownLinks=current;state.selectedLinks=(saved.version===2&&Array.isArray(saved.selectedLinks)?saved.selectedLinks:current).filter(link=>currentSet.has(link));state.flows=(saved.flows||[]).filter(flow=>campaigns.has(flow.campaign_code)&&adsets.get(flow.adset_code)?.campaignBundleCode===flow.campaign_code).map(flow=>({...flow,id:flow.id||crypto.randomUUID(),link_urls:(Array.isArray(flow.link_urls)?flow.link_urls:current).filter(link=>currentSet.has(link)),start_time:flow.start_time||defaultLocalDateTime(),end_time:flow.end_time||null}));els.adName.value=String(saved.adName||'');return Boolean(state.flows.length||els.links.value.trim());}catch(_error){return false;}}

function renderCampaigns(){els.campaigns.innerHTML=state.catalog.campaigns.map(c=>`<button class="choice ${state.campaign===c.code?'selected':''}" data-campaign="${c.code}"><strong>${escapeHtml(c.objectiveName||c.name)}</strong><small>${escapeHtml(c.description||'')}</small></button>`).join('');}
function renderLocations(){if(!state.campaign){els.locations.className='location-list empty-state';els.locations.textContent='Chọn chiến dịch trước';return;}const groups=[...new Set(state.catalog.adsets.filter(a=>a.campaignBundleCode===state.campaign).map(a=>a.conversionLocation))];els.locations.className='location-list';els.locations.innerHTML=groups.map(name=>`<button class="location-chip ${state.location===name?'selected':''}" data-location="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join('');}
function renderAdsets(){if(!state.location){els.adsets.className='choice-list adset-list empty-state';els.adsets.textContent='Chọn vị trí chuyển đổi';return;}const items=state.catalog.adsets.filter(a=>a.campaignBundleCode===state.campaign&&a.conversionLocation===state.location);els.adsets.className='choice-list adset-list';els.adsets.innerHTML=items.map(a=>`<button class="choice ${state.adset===a.code?'selected':''}" data-adset="${a.code}"><strong>${escapeHtml(a.performanceGoal||a.name)}</strong><small>${escapeHtml(a.summary||'')}</small></button>`).join('');}
function allowedAudiences(){const campaign=byCode(state.catalog.campaigns,state.campaign);const allowed=new Set(campaign?.allowedAudiencePresetCodes||[]);return state.catalog.audiences.filter(x=>!allowed.size||allowed.has(x.code));}
function openSetup(){const campaign=byCode(state.catalog.campaigns,state.campaign);const adset=byCode(state.catalog.adsets,state.adset);if(!campaign||!adset)return;els.selection.classList.add('hidden');els.setup.classList.remove('hidden');els.path.textContent='';const strong=document.createElement('strong');strong.textContent=`${campaign.objectiveName||campaign.name} → ${adset.conversionLocation} → ${adset.performanceGoal} · ${selectedLinks().length} bài`;els.path.append(strong,els.changeSelection);optionList(els.audience,allowedAudiences(),'Chọn nhóm người xem bắt buộc');const datasets=adset.requiresDataset?state.catalog.datasets.filter(item=>item.code!=='DATASET_NONE'):state.catalog.datasets;optionList(els.dataset,datasets,adset.requiresDataset?'Chọn nguồn dữ liệu bắt buộc':'Không chọn nguồn dữ liệu');els.datasetHint.textContent=adset.requiresDataset?'Bắt buộc':'';optionList(els.budget,state.catalog.budgets,'Chọn mức thường dùng');optionList(els.placement,state.catalog.placements,'Không chọn vị trí hiển thị');if(adset.requiresDataset&&datasets[0])els.dataset.value=datasets[0].code;else if(state.catalog.datasets[0])els.dataset.value=state.catalog.datasets[0].code;if(state.catalog.budgets[0]){els.budget.value=state.catalog.budgets[0].code;applyBudgetPreset();}if(state.catalog.placements[0])els.placement.value=state.catalog.placements[0].code;els.startTime.value=defaultLocalDateTime();els.hasEndTime.checked=false;els.endTime.value='';toggleEndTime();}
function closeSetup(){els.setup.classList.add('hidden');els.selection.classList.remove('hidden');}
function resetDraft(){state.location=null;state.adset=null;state.editingFlowId=null;$('addFlowButton').textContent='+ Thêm cách chạy vào kế hoạch';els.changeSelection.textContent='Đổi lựa chọn';els.budgetAmount.value='';els.startTime.value='';els.hasEndTime.checked=false;els.hasEndTime.disabled=false;els.endTime.value='';toggleEndTime();renderLocations();renderAdsets();closeSetup();}
function flowLabel(flow){const c=byCode(state.catalog.campaigns,flow.campaign_code);const a=byCode(state.catalog.adsets,flow.adset_code);return `${c?.objectiveName||c?.name||''} → ${a?.conversionLocation||''} → ${a?.performanceGoal||''}`;}
function addFlow(){const adset=byCode(state.catalog.adsets,state.adset);if(!adset)return;const assignedLinks=selectedLinks();if(!assignedLinks.length){showToast('Hãy chọn ít nhất một bài viết cho flow này.',true);els.linkSelection.focus();return;}if(!els.audience.value){showToast('Hãy chọn một nhóm người xem cho cách chạy này.',true);els.audience.focus();return;}if(adset.requiresDataset&&(!els.dataset.value||els.dataset.value==='DATASET_NONE')){showToast('Nhóm quảng cáo này bắt buộc chọn nguồn dữ liệu.',true);els.dataset.focus();return;}const custom={};const rawAmount=els.budgetAmount.value.trim();const normalizedAmount=rawAmount.replace(',','.');if(!rawAmount||!/^\d+(?:[.,]\d+)?$/.test(rawAmount)||Number(normalizedAmount)<=0){showToast('Số tiền tùy chỉnh phải là một số lớn hơn 0.',true);els.budgetAmount.focus();return;}if(!els.startTime.value){showToast('Hãy chọn thời gian bắt đầu.',true);els.startTime.focus();return;}if(els.budgetType.value==='Ngân sách trọn đời'&&!els.endTime.value){showToast('Ngân sách trọn đời bắt buộc phải có thời gian kết thúc.',true);els.endTime.focus();return;}if(els.endTime.value&&new Date(els.endTime.value)<=new Date(els.startTime.value)){showToast('Thời gian kết thúc phải sau thời gian bắt đầu.',true);els.endTime.focus();return;}custom[els.budgetType.value]=normalizedAmount;const flow={id:state.editingFlowId||crypto.randomUUID(),campaign_code:state.campaign,adset_code:state.adset,link_urls:assignedLinks,audience_codes:[els.audience.value],dataset_code:els.dataset.value||null,budget_code:els.budget.value||null,custom_budget_values:custom,start_time:els.startTime.value,end_time:els.hasEndTime.checked?els.endTime.value:null,placement_code:els.placement.value||null,creative_mode:'existing_post'};if(state.editingFlowId){const index=state.flows.findIndex(item=>item.id===state.editingFlowId);if(index>=0)state.flows[index]=flow;showToast('Đã cập nhật flow.');}else{state.flows.push(flow);showToast(`Đã áp dụng flow cho ${assignedLinks.length} bài.`);}resetDraft();saveLocalPlan();renderPlan();}
function editFlow(id){const flow=state.flows.find(item=>item.id===id);if(!flow)return;const adset=byCode(state.catalog.adsets,flow.adset_code);if(!adset)return;state.editingFlowId=id;state.selectedLinks=(flow.link_urls||links()).filter(link=>links().includes(link));state.campaign=flow.campaign_code;state.location=adset.conversionLocation;state.adset=flow.adset_code;renderLinkSelection();renderCampaigns();renderLocations();renderAdsets();openSetup();els.changeSelection.textContent='Hủy chỉnh sửa';els.audience.value=flow.audience_codes?.[0]||'';els.dataset.value=flow.dataset_code||'';els.budget.value=flow.budget_code||'';els.placement.value=flow.placement_code||'';const custom=flow.custom_budget_values||{};if(custom['Ngân sách trọn đời']!==undefined){els.budgetType.value='Ngân sách trọn đời';els.budgetAmount.value=custom['Ngân sách trọn đời'];}else{els.budgetType.value='Ngân sách/ngày';els.budgetAmount.value=custom['Ngân sách/ngày']??'';}els.startTime.value=(flow.start_time||defaultLocalDateTime()).slice(0,16);els.hasEndTime.checked=Boolean(flow.end_time);els.endTime.value=(flow.end_time||'').slice(0,16);toggleEndTime();$('addFlowButton').textContent='Lưu thay đổi cách chạy';}
function changeOrCancelSelection(){if(state.editingFlowId){resetDraft();showToast('Đã hủy chỉnh sửa, cách chạy cũ được giữ nguyên.');return;}closeSetup();}
function duplicateFlow(id){const source=state.flows.find(f=>f.id===id);if(source)state.flows.push({...structuredClone(source),id:crypto.randomUUID()});saveLocalPlan();renderPlan();}
function removeFlow(id){state.flows=state.flows.filter(f=>f.id!==id);if(state.editingFlowId===id)resetDraft();saveLocalPlan();renderPlan();}
function creativePreviewHtml(link){const preview=state.creativePreviews[link];if(!preview)return'';if(preview.status==='loading')return'<span class="creative-preview-status"><i class="preview-spinner" aria-hidden="true"></i>Đang đọc creative…</span>';if(preview.status!=='ready')return'<span class="creative-preview-status unavailable">Không xem được preview · vẫn có thể lập kế hoạch</span>';const thumbnail=preview.thumbnail_url?`<img src="${escapeHtml(preview.thumbnail_url)}" alt="" width="64" height="64" loading="lazy" referrerpolicy="no-referrer">`:'<span class="creative-no-image" aria-hidden="true">POST</span>';return `<span class="creative-preview">${thumbnail}<span class="creative-preview-copy"><b>${escapeHtml(preview.page_name||'Facebook Page')}</b><em>${escapeHtml(preview.message||`Bài ${preview.media_type||'Facebook'}`)}</em><small>${escapeHtml(preview.media_type||'post')}</small></span></span>`;}
function renderLinkSelection(){const current=links(),selected=new Set(selectedLinks());els.selectedLinkCount.textContent=`${selected.size}/${current.length} bài đang chọn`;if(!current.length){els.linkSelection.className='link-selection-list empty-state';els.linkSelection.textContent='Dán link để chọn bài cần áp dụng';return;}els.linkSelection.className='link-selection-list';els.linkSelection.innerHTML=current.map((link,index)=>`<label class="link-select-card ${selected.has(link)?'selected':''}"><input type="checkbox" data-plan-link-index="${index}" ${selected.has(link)?'checked':''}><span class="link-select-content"><strong>Bài ${index+1}</strong><small title="${escapeHtml(link)}">${escapeHtml(link)}</small>${creativePreviewHtml(link)}</span></label>`).join('');}
async function loadCreativePreviews(requestLinks){const requestId=++state.creativePreviewRequest;try{const data=await api('/api/meta/creative-previews',{method:'POST',body:JSON.stringify({links:requestLinks})});if(requestId!==state.creativePreviewRequest)return;(data.previews||[]).forEach(preview=>{if(preview?.link)state.creativePreviews[preview.link]=preview;});}catch(error){if(requestId!==state.creativePreviewRequest)return;requestLinks.forEach(link=>{state.creativePreviews[link]={link,status:'unavailable',error:error.message};});}renderLinkSelection();}
function scheduleCreativePreviews(){clearTimeout(state.creativePreviewTimer);const current=links(),currentSet=new Set(current);Object.keys(state.creativePreviews).forEach(link=>{if(!currentSet.has(link))delete state.creativePreviews[link];});const requestLinks=current.filter(isFacebookLink).filter(link=>state.creativePreviews[link]?.status!=='ready');if(!requestLinks.length){renderLinkSelection();return;}requestLinks.forEach(link=>{state.creativePreviews[link]={link,status:'loading'};});renderLinkSelection();state.creativePreviewTimer=setTimeout(()=>loadCreativePreviews(requestLinks),450);}
function renderFlows(){if(!state.flows.length){els.flows.className='flow-list empty-state';els.flows.textContent='Chưa có flow';return;}els.flows.className='flow-list';els.flows.innerHTML=state.flows.map((flow,i)=>{const audience=byCode(state.catalog.audiences,flow.audience_codes?.[0]);const dataset=byCode(state.catalog.datasets,flow.dataset_code);const placement=byCode(state.catalog.placements,flow.placement_code);const assigned=(flow.link_urls||links()).length;return `<div class="flow-card"><div class="flow-main"><strong title="${escapeHtml(flowLabel(flow))}">${i+1}. ${escapeHtml(flowLabel(flow))}</strong><div class="flow-meta"><span class="tag">${assigned} bài</span>${audience?`<span class="tag purple">${escapeHtml(audience.name)}</span>`:''}<span class="tag orange">${escapeHtml(budgetSummary(flow))}</span><span class="tag">${escapeHtml(scheduleSummary(flow))}</span>${dataset&&dataset.code!=='DATASET_NONE'?`<span class="tag">${escapeHtml(dataset.name)}</span>`:''}${placement?`<span class="tag green">${escapeHtml(placement.name)}</span>`:''}</div></div><button class="icon-button" data-edit="${flow.id}">Sửa</button><button class="icon-button" data-copy="${flow.id}">Chép</button><button class="icon-button danger" data-delete="${flow.id}">Xóa</button></div>`;}).join('');}
function renderArticles(){const currentLinks=links();if(!currentLinks.length){els.articles.className='article-list empty-state';els.articles.textContent='Dán đường dẫn bài viết để bắt đầu';return;}els.articles.className='article-list';els.articles.innerHTML=currentLinks.map((link,i)=>{const valid=isFacebookLink(link);const flowGroups=state.flows.map((flow,flowIndex)=>{const adset=byCode(state.catalog.adsets,flow.adset_code);const audience=byCode(state.catalog.audiences,flow.audience_codes[0]);const dataset=byCode(state.catalog.datasets,flow.dataset_code);const placement=byCode(state.catalog.placements,flow.placement_code);return `<div class="article-flow"><b>Cách chạy ${flowIndex+1}</b><div class="tags"><span class="tag">${escapeHtml(adset?.conversionLocation||'')}</span><span class="tag green">${escapeHtml(adset?.performanceGoal||'')}</span>${audience?`<span class="tag purple">${escapeHtml(audience.name)}</span>`:''}<span class="tag orange">${escapeHtml(budgetSummary(flow))}</span><span class="tag">${escapeHtml(scheduleSummary(flow))}</span>${dataset?`<span class="tag">${escapeHtml(dataset.name)}</span>`:''}${placement?`<span class="tag">${escapeHtml(placement.name)}</span>`:''}</div></div>`;}).join('');return `<article class="article-card ${valid?'':'invalid-link'}"><div class="article-head"><strong>Bài ${i+1} · ${valid?'Hợp lệ':'Link không hợp lệ'}</strong><span title="${escapeHtml(link)}">${escapeHtml(link)}</span></div>${flowGroups||'<span class="empty-state">Chưa gán cách chạy</span>'}</article>`;}).join('');}
function renderPlan(){const currentLinks=links(),count=currentLinks.length,invalid=currentLinks.filter(link=>!isFacebookLink(link)).length,total=count*state.flows.reduce((n,f)=>n+Math.max(1,f.audience_codes.length),0),ready=count>0&&state.flows.length>0&&invalid===0,missing=Number(count===0)+Number(state.flows.length===0)+Number(invalid>0);$('linkCount').textContent=count?`${count} bài viết${invalid?` · ${invalid} link không hợp lệ`:''}`:'Chưa có bài viết';$('linkCount').classList.toggle('error-text',invalid>0);els.summary.textContent=`${count} bài · ${state.flows.length} cách chạy · ${total} mục`;els.readiness.textContent=ready?'Sẵn sàng gửi duyệt':invalid?`Có ${invalid} đường dẫn không hợp lệ`:`Còn thiếu ${missing} mục`;els.readiness.classList.toggle('ready',ready);els.actionSummary.textContent=ready?`${total} quảng cáo sẽ được gửi duyệt`:'Chưa đủ dữ liệu';els.actionHint.textContent=ready?`${count} bài viết × ${state.flows.length} cách chạy`:invalid?'Sửa đường dẫn được đánh dấu lỗi':'Thêm bài viết và ít nhất một cách chạy';els.previewButton.disabled=!ready;els.createButton.disabled=!ready;renderFlows();renderArticles();}
function renderAssignedArticles(){const currentLinks=links();if(!currentLinks.length){els.articles.className='article-list empty-state';els.articles.textContent='Dán đường dẫn bài viết để bắt đầu';return;}els.articles.className='article-list';els.articles.innerHTML=currentLinks.map((link,i)=>{const valid=isFacebookLink(link);const flowGroups=state.flows.map((flow,flowIndex)=>({flow,flowIndex})).filter(({flow})=>(flow.link_urls||currentLinks).includes(link)).map(({flow,flowIndex})=>{const adset=byCode(state.catalog.adsets,flow.adset_code);const audience=byCode(state.catalog.audiences,flow.audience_codes[0]);const dataset=byCode(state.catalog.datasets,flow.dataset_code);const placement=byCode(state.catalog.placements,flow.placement_code);return `<div class="article-flow"><b>Flow ${flowIndex+1}</b><div class="tags"><span class="tag">${escapeHtml(adset?.conversionLocation||'')}</span><span class="tag green">${escapeHtml(adset?.performanceGoal||'')}</span>${audience?`<span class="tag purple">${escapeHtml(audience.name)}</span>`:''}<span class="tag orange">${escapeHtml(budgetSummary(flow))}</span><span class="tag">${escapeHtml(scheduleSummary(flow))}</span>${dataset?`<span class="tag">${escapeHtml(dataset.name)}</span>`:''}${placement?`<span class="tag green">${escapeHtml(placement.name)}</span>`:''}</div></div>`;}).join('');return `<article class="article-card ${valid?'':'invalid-link'}"><div class="article-head"><strong>Bài ${i+1} · ${valid?'Hợp lệ':'Link không hợp lệ'}</strong><span title="${escapeHtml(link)}">${escapeHtml(link)}</span></div>${flowGroups||'<span class="empty-state">Chưa gán flow</span>'}</article>`;}).join('');}
function renderAssignedPlan(){const currentLinks=links(),count=currentLinks.length,invalid=currentLinks.filter(link=>!isFacebookLink(link)).length,total=state.flows.reduce((sum,flow)=>sum+((flow.link_urls||currentLinks).length*Math.max(1,flow.audience_codes.length)),0),unassignedFlows=state.flows.filter(flow=>!(flow.link_urls||currentLinks).length).length,ready=count>0&&state.flows.length>0&&total>0&&invalid===0&&unassignedFlows===0,missing=Number(count===0)+Number(state.flows.length===0)+Number(invalid>0)+Number(unassignedFlows>0);$('linkCount').textContent=count?`${count} bài viết${invalid?` · ${invalid} link không hợp lệ`:''}`:'Chưa có bài viết';$('linkCount').classList.toggle('error-text',invalid>0);els.summary.textContent=`${count} bài · ${state.flows.length} flow · ${total} mục`;els.readiness.textContent=ready?'Sẵn sàng gửi duyệt':invalid?`Có ${invalid} đường dẫn không hợp lệ`:unassignedFlows?`${unassignedFlows} flow chưa có bài`:`Còn thiếu ${missing} mục`;els.readiness.classList.toggle('ready',ready);els.actionSummary.textContent=ready?`${total} quảng cáo sẽ được gửi duyệt`:'Chưa đủ dữ liệu';els.actionHint.textContent=ready?`${total} quảng cáo từ ${count} bài đã dán`:invalid?'Sửa đường dẫn được đánh dấu lỗi':'Chọn bài và thêm từng flow';els.previewButton.disabled=!ready;els.createButton.disabled=!ready;renderLinkSelection();renderFlows();renderAssignedArticles();}
function payload(){return{links:links(),flows:state.flows.map(({id,...flow})=>flow),ad_name:els.adName.value.trim()};}
function showExportView(){
  $('plannerWorkspace').classList.add('hidden');$('plannerActionbar').classList.add('hidden');$('exportView').classList.remove('hidden');$('reviewExportButton').classList.add('hidden');$('resetButton').classList.add('hidden');$('backToPlannerButton').classList.remove('hidden');document.querySelector('.page-heading h1').textContent='Duyệt và xuất CSV Meta';document.querySelector('.page-heading p').textContent='Chọn đúng các bài đã duyệt trên Notion để xuất.';loadCandidates();
}
function showPlannerView(){
  $('exportView').classList.add('hidden');$('plannerWorkspace').classList.remove('hidden');$('plannerActionbar').classList.remove('hidden');$('reviewExportButton').classList.remove('hidden');$('resetButton').classList.remove('hidden');$('backToPlannerButton').classList.add('hidden');document.querySelector('.page-heading h1').textContent='Lập kế hoạch quảng cáo';document.querySelector('.page-heading p').textContent='Thêm bài viết và cấu hình từng cách chạy trong một màn hình.';
}
function selectedCandidateIds(){return [...document.querySelectorAll('[data-candidate-id]:checked')].map(input=>input.dataset.candidateId);}
function updateExportSelection(){const selected=selectedCandidateIds().length;$('exportSelectedButton').disabled=selected===0;$('exportSelectedButton').textContent=selected?`Xuất ${selected} bài đã chọn`:'Xuất các bài đã chọn';$('selectAllCandidates').checked=Boolean(state.candidates.length&&selected===state.candidates.length);}
function renderCandidates(){const host=$('candidateList');$('candidateCount').textContent=`${state.candidates.length} bài đủ điều kiện`;if(!state.candidates.length){host.className='candidate-list empty-state';host.textContent='Không có bài Hoàn thành nào đang chờ xuất.';updateExportSelection();return;}host.className='candidate-list';host.innerHTML=state.candidates.map(item=>`<article class="candidate-card"><input type="checkbox" data-candidate-id="${escapeHtml(item.id)}"><div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.campaign)} · ${escapeHtml(item.adset)}</p><p>${escapeHtml(item.audience)}${item.budget?` · Ngân sách ${escapeHtml(item.budget)}`:''}</p><p title="${escapeHtml(item.post_url)}">${escapeHtml(item.post_url)}</p><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">Mở Notion</a></div><span class="candidate-status">${escapeHtml(item.status)}</span></article>`).join('');updateExportSelection();}
async function loadCandidates(){const host=$('candidateList');host.className='candidate-list empty-state';host.textContent='Đang đọc bài đã duyệt từ Notion…';$('refreshCandidatesButton').disabled=true;$('exportResult').classList.add('hidden');try{const data=await api('/api/export/candidates');state.candidates=data.candidates||[];renderCandidates();}catch(error){host.textContent=error.message;showToast(error.message,true);}finally{$('refreshCandidatesButton').disabled=false;}}
async function exportSelected(){const pageIds=selectedCandidateIds();if(!pageIds.length)return;if(!confirm(`Xuất ${pageIds.length} bài đã chọn và đánh dấu đã xuất trên Notion?`))return;const button=$('exportSelectedButton');button.disabled=true;button.textContent='Đang tạo CSV Meta…';try{const data=await api('/api/export',{method:'POST',body:JSON.stringify({page_ids:pageIds})});const result=$('exportResult');result.innerHTML=`Đã xuất <strong>${data.count}</strong> quảng cáo. <a href="${escapeHtml(data.download_url)}">Tải file ${escapeHtml(data.file_name)}</a>${data.sync_warning?`<br><small>Cảnh báo đồng bộ: ${escapeHtml(data.sync_warning)}</small>`:''}`;result.classList.remove('hidden');await loadCandidates();result.classList.remove('hidden');}catch(error){showToast(error.message,true);}finally{button.textContent='Xuất các bài đã chọn';updateExportSelection();}}
async function preview(){els.previewButton.disabled=true;els.previewButton.textContent='Đang dựng kế hoạch…';try{const requestPayload=payload();const data=await api('/api/planner/preview',{method:'POST',body:JSON.stringify(requestPayload)});state.preview=data.plan;state.previewPayload=JSON.stringify(requestPayload);const p=data.plan;const campaigns=new Set(p.flows.map(flow=>flow.campaign_code));$('previewContent').innerHTML=`<p><strong>${campaigns.size}</strong> campaign · <strong>${p.flows.length}</strong> nhóm quảng cáo · <strong>${p.items.length}</strong> quảng cáo</p><p><small>Sau khi gửi, IT/Ads Operator sẽ kiểm tra toàn bộ cây trước khi tạo PAUSED trên Meta.</small></p>`+p.flows.map((f,i)=>`<div class="preview-row"><strong>${i+1}. ${escapeHtml(f.campaign_name)}</strong><br>${escapeHtml(f.adset_name)}<br><small>${escapeHtml(f.audiences.join(', '))} · ${escapeHtml(f.placement)} · ${escapeHtml(f.start_time||'Chưa đặt lịch')} → ${escapeHtml(f.end_time||'Không giới hạn')}</small></div>`).join('');$('previewDialog').showModal();}catch(e){state.preview=null;state.previewPayload=null;showToast(e.message,true);}finally{els.previewButton.textContent='Xem trước';renderPlan();}}
async function createDrafts(){const requestPayload=payload();els.createButton.disabled=true;els.createButton.textContent='Đang gửi kế hoạch…';try{const data=await api('/api/reviews',{method:'POST',body:JSON.stringify(requestPayload)});showToast(data.deduplicated?'Kế hoạch này đã được gửi trước đó.':'Đã gửi kế hoạch cho IT/Ads Operator duyệt.');await showAppView('reviews');await selectReview(data.review.id);}catch(e){showToast(e.message,true);}finally{els.createButton.textContent='Gửi kế hoạch duyệt';renderPlan();}}
function resetPlan(){if(state.flows.length||links().length){if(!confirm('Xóa kế hoạch đang nhập để làm kế hoạch mới?'))return;}state.flows=[];state.campaign=null;state.location=null;state.adset=null;state.editingFlowId=null;state.selectedLinks=[];state.knownLinks=[];state.creativePreviews={};clearTimeout(state.creativePreviewTimer);state.creativePreviewRequest+=1;els.links.value='';els.adName.value='';localStorage.removeItem(LOCAL_PLAN_KEY);closeSetup();renderCampaigns();renderLocations();renderAdsets();renderPlan();}

const REVIEW_STATUS={
  PENDING_REVIEW:{label:'Chờ duyệt',className:''},
  APPROVED:{label:'Đã duyệt',className:'approved'},
  REJECTED:{label:'Từ chối',className:'rejected'},
  PUBLISHING:{label:'Đang tạo Meta',className:'approved'},
  META_CREATED:{label:'Đã tạo PAUSED',className:'created'}
};
function reviewStatus(status){return REVIEW_STATUS[status]||{label:status,className:''};}
function formatReviewTime(value){if(!value)return'';try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));}catch(_error){return value;}}
function renderAuth(){const authenticated=Boolean(state.auth.authenticated);$('reviewRole').textContent=authenticated?`Người duyệt: ${state.auth.reviewer}`:'Chế độ Content';$('reviewRoleHint').textContent=authenticated?'Có quyền duyệt, từ chối và tạo PAUSED trên Meta.':'Có thể gửi và theo dõi kế hoạch.';$('approverLoginButton').classList.toggle('hidden',authenticated);$('approverLogoutButton').classList.toggle('hidden',!authenticated);renderReviewDetail();}
async function loadAuth(){const data=await api('/api/auth/me');state.auth=data;renderAuth();}
function renderReviewList(){const visible=state.reviews.filter(item=>state.reviewFilter==='ALL'||item.status===state.reviewFilter);$('reviewCount').textContent=`${state.reviews.length} kế hoạch · ${state.reviews.filter(item=>item.status==='PENDING_REVIEW').length} chờ duyệt`;const host=$('reviewList');if(!visible.length){host.className='review-list empty-state';host.textContent='Không có kế hoạch ở trạng thái này.';return;}host.className='review-list';host.innerHTML=visible.map(item=>{const status=reviewStatus(item.status);return `<button class="review-card ${state.selectedReview?.id===item.id?'selected':''}" type="button" data-review-id="${escapeHtml(item.id)}"><span class="review-card-head"><strong>${escapeHtml(item.summary.campaigns_count)} campaign · ${escapeHtml(item.summary.ads_count)} ads</strong><span class="review-status ${status.className}">${escapeHtml(status.label)}</span></span><small>${escapeHtml(item.submitted_by)} · ${escapeHtml(formatReviewTime(item.submitted_at))}</small><small>Mã: ${escapeHtml(item.id.slice(0,8))}</small></button>`;}).join('');}
async function loadReviews(){const host=$('reviewList');host.className='review-list empty-state';host.textContent='Đang tải kế hoạch…';$('refreshReviewsButton').disabled=true;try{const data=await api('/api/reviews');state.reviews=data.reviews||[];renderReviewList();}catch(error){host.textContent=error.message;showToast(error.message,true);}finally{$('refreshReviewsButton').disabled=false;}}
function renderReviewTree(review){$('reviewTree').innerHTML=(review.tree||[]).map(campaign=>`<article class="review-campaign"><header><strong>Campaign · ${escapeHtml(campaign.name)}</strong><small>${escapeHtml(campaign.code)}</small></header>${campaign.adsets.map(adset=>`<section class="review-adset"><header><strong>Nhóm quảng cáo ${escapeHtml(adset.position)} · ${escapeHtml(adset.name)}</strong><span>${escapeHtml(adset.conversion_location)} → ${escapeHtml(adset.performance_goal)}</span><div class="review-adset-meta"><span class="tag purple">${escapeHtml((adset.audiences||[]).join(', '))}</span><span class="tag orange">${escapeHtml(Object.entries(adset.custom_budget_values||{}).map(([key,value])=>`${value} · ${key}`).join(', ')||adset.budget)}</span><span class="tag green">${escapeHtml(adset.placement)}</span><span class="tag">${escapeHtml(adset.start_time||'Chưa đặt lịch')} → ${escapeHtml(adset.end_time||'Không giới hạn')}</span></div></header><div class="review-ads">${adset.ads.map(ad=>`<div class="review-ad"><i>${escapeHtml(ad.position)}</i><a href="${escapeHtml(ad.link)}" target="_blank" rel="noreferrer" title="${escapeHtml(ad.link)}">${escapeHtml(ad.name)} · ${escapeHtml(ad.link)}</a></div>`).join('')}</div></section>`).join('')}</article>`).join('');}
function renderReviewDetail(){const review=state.selectedReview;$('emptyReviewDetail').classList.toggle('hidden',Boolean(review));$('reviewDetail').classList.toggle('hidden',!review);if(!review)return;const status=reviewStatus(review.status);const badge=$('reviewDetailStatus');badge.textContent=status.label;badge.className=`review-status ${status.className}`;$('reviewDetailTitle').textContent=`Kế hoạch ${review.id.slice(0,8)}`;$('reviewDetailMeta').textContent=`${review.submitted_by} gửi lúc ${formatReviewTime(review.submitted_at)}`;$('reviewTotals').innerHTML=`<span class="review-total">${review.summary.campaigns_count} campaign</span><span class="review-total">${review.summary.adsets_count} nhóm</span><span class="review-total">${review.summary.ads_count} ads</span>`;renderReviewTree(review);const note=$('reviewNote');note.classList.toggle('hidden',!review.reviewer_note);note.textContent=review.reviewer_note?`Ghi chú của ${review.reviewed_by||'người duyệt'}: ${review.reviewer_note}`:'';const canAct=state.auth.authenticated&&['PENDING_REVIEW','APPROVED'].includes(review.status);$('reviewActions').classList.toggle('hidden',!canAct);$('approveReviewButton').classList.toggle('hidden',review.status!=='PENDING_REVIEW');$('rejectReviewButton').classList.toggle('hidden',review.status!=='PENDING_REVIEW');$('publishReviewButton').classList.toggle('hidden',review.status!=='APPROVED');}
async function selectReview(reviewId){try{const data=await api(`/api/reviews/${encodeURIComponent(reviewId)}`);state.selectedReview=data.review;renderReviewList();renderReviewDetail();}catch(error){showToast(error.message,true);}}
async function reviewAction(action){const review=state.selectedReview;if(!review)return;const note=$('reviewerNote').value.trim();if(action==='reject'&&!note){showToast('Hãy nhập lý do từ chối.',true);$('reviewerNote').focus();return;}if(action==='publish'&&!confirm('Tạo toàn bộ campaign, nhóm quảng cáo và quảng cáo ở trạng thái PAUSED trên Meta?'))return;const button=action==='approve'?$('approveReviewButton'):action==='reject'?$('rejectReviewButton'):$('publishReviewButton');const oldText=button.textContent;button.disabled=true;button.textContent=action==='publish'?'Đang tạo PAUSED…':'Đang lưu…';try{const data=await api(`/api/reviews/${encodeURIComponent(review.id)}/${action}`,{method:'POST',body:JSON.stringify({note})});state.selectedReview=data.review;$('reviewerNote').value='';await loadReviews();renderReviewDetail();showToast(action==='approve'?'Đã duyệt kế hoạch.':action==='reject'?'Đã từ chối kế hoạch.':'Đã tạo kế hoạch PAUSED trên Meta.');}catch(error){showToast(error.message,true);}finally{button.disabled=false;button.textContent=oldText;}}
async function loginApprover(event){event.preventDefault();const button=$('approverSubmitButton');button.disabled=true;try{const data=await api('/api/auth/approver',{method:'POST',body:JSON.stringify({reviewer:$('approverName').value.trim(),key:$('approverKey').value})});state.auth=data;$('approverKey').value='';$('approverDialog').close();renderAuth();showToast('Đã đăng nhập quyền người duyệt.');}catch(error){showToast(error.message,true);}finally{button.disabled=false;}}
function closeApproverDialog(){$('approverKey').value='';$('approverDialog').close();}
async function logoutApprover(){try{await api('/api/auth/session',{method:'DELETE'});state.auth={authenticated:false,role:'content',csrf_token:null};renderAuth();showToast('Đã đăng xuất quyền người duyệt.');}catch(error){showToast(error.message,true);}}

const PRESET_META={
  audiences:{title:'Tệp đối tượng',subtitle:'Thiết lập Kiểm soát và Gợi ý đối tượng như Meta, sau đó chọn lại trong Planner.',prefix:'AUD_',fields:[['Mẫu đối tượng','Tên mẫu đối tượng'],['Vị trí địa lý','Vị trí địa lý'],['Tuổi kiểm soát min','Tuổi kiểm soát nhỏ nhất','number'],['Ngôn ngữ','Ngôn ngữ'],['Loại trừ đối tượng','Loại trừ đối tượng'],['Đối tượng tuỳ chỉnh','Đối tượng tùy chỉnh'],['Tuổi min','Tuổi gợi ý nhỏ nhất','number'],['Tuổi max','Tuổi gợi ý lớn nhất','number'],['Giới tính','Giới tính'],['Nhắm mục tiêu chi tiết','Nhắm mục tiêu chi tiết']]},
  placements:{title:'Vị trí quảng cáo',subtitle:'Hoàn thiện bundle nơi hiển thị để Planner chỉ cần chọn.',prefix:'PLC_',fields:[['Nền tảng quảng cáo','Nền tảng quảng cáo'],['Vị trí Facebook','Vị trí trên Facebook'],['Vị trí Messenger','Vị trí trên Messenger'],['Thiết bị','Thiết bị'],['Mở rộng nhắm chọn','Mở rộng nhắm chọn']]},
  budgets:{title:'Ngân sách',subtitle:'Lưu các mức ngân sách thường dùng để áp dụng nhất quán.',prefix:'BUD_',fields:[['Loại ngân sách','Loại ngân sách','select',['Daily','Lifetime']],['Ngân sách/ngày','Ngân sách mỗi ngày','number'],['Ngân sách trọn đời','Ngân sách trọn đời','number'],['Tính phí theo','Cách tính phí']]}
};
function presetFieldHtml([key,label,type='text',options=[]]){const control=type==='select'?`<select data-preset-field="${escapeHtml(key)}">${options.map(item=>`<option value="${item}">${item}</option>`).join('')}</select>`:`<input data-preset-field="${escapeHtml(key)}" type="${type}" ${type==='number'?'min="0" step="any"':''}>`;return `<label>${escapeHtml(label)}${control}</label>`;}
function audienceAgeOptions(selected,min=18,max=65){let html='';for(let age=min;age<=max;age++)html+=`<option value="${age}" ${Number(selected)===age?'selected':''}>${age}</option>`;return html;}
function audienceOption(value,label,current){return `<option value="${escapeHtml(value)}" ${String(current??'')===String(value)?'selected':''}>${escapeHtml(label)}</option>`;}
function audienceCustomOptions(current){const options=[audienceOption('','Không chọn · có thể để trống',current)];for(const item of state.catalog.audiences||[]){const value=item.notionValues?.['Đối tượng tuỳ chỉnh'];if(value)options.push(audienceOption(value,item.name,current));}if(current&&!options.some(option=>option.includes(`value="${escapeHtml(current)}"`)))options.push(audienceOption(current,current,current));return options.join('');}
function audienceFieldsHtml(preset){const values=preset?.notionValues||{};const location=values['Vị trí địa lý']||'Phan Thiet, Bình Thuận Province, Vietnam +25km';const controlAge=values['Tuổi kiểm soát min']??values['Tuổi min']??18;const ageMin=values['Tuổi min']??18;const ageMax=values['Tuổi max']??45;const gender=values['Giới tính']||'Tất cả';const detail=values['Nhắm mục tiêu chi tiết']||'';return `<div class="audience-composer">
  <input type="hidden" data-preset-field="Mẫu đối tượng" value="${escapeHtml(values['Mẫu đối tượng']||preset?.name||'')}">
  <section class="audience-section audience-controls"><header><span class="audience-section-number">1</span><div><h3>Kiểm soát đối tượng</h3><p>Giới hạn bắt buộc Meta không được mở rộng ra ngoài.</p></div></header>
    <div class="audience-field-grid">
      <label class="wide">Vị trí địa lý<select data-preset-field="Vị trí địa lý">${audienceOption('Phan Thiet, Bình Thuận Province, Vietnam +25km','Phan Thiết · bán kính 25 km',location)}${audienceOption('Bình Thuận Province, Vietnam','Bình Thuận',location)}${audienceOption('Vietnam','Việt Nam',location)}${!['Phan Thiet, Bình Thuận Province, Vietnam +25km','Bình Thuận Province, Vietnam','Vietnam'].includes(location)?audienceOption(location,location,location):''}</select></label>
      <label>Tuổi tối thiểu<select data-preset-field="Tuổi kiểm soát min">${audienceAgeOptions(controlAge)}</select></label>
      <label>Ngôn ngữ<select data-preset-field="Ngôn ngữ">${audienceOption('','Tất cả ngôn ngữ',values['Ngôn ngữ']||'')}${audienceOption('Tiếng Việt','Tiếng Việt',values['Ngôn ngữ']||'')}</select></label>
      <label class="wide">Loại trừ đối tượng <small>Không bắt buộc</small><select data-preset-field="Loại trừ đối tượng">${audienceCustomOptions(values['Loại trừ đối tượng']||'')}</select></label>
    </div>
  </section>
  <section class="audience-section audience-suggestions"><header><span class="audience-section-number">2</span><div><h3>Gợi ý đối tượng</h3><p>Meta ưu tiên tìm trong nhóm này nhưng có thể mở rộng để tối ưu.</p></div></header>
    <div class="audience-field-grid">
      <label class="wide">Đối tượng tùy chỉnh <small>Không bắt buộc</small><select data-preset-field="Đối tượng tuỳ chỉnh">${audienceCustomOptions(values['Đối tượng tuỳ chỉnh']||'')}</select></label>
      <label>Tuổi từ<select data-preset-field="Tuổi min">${audienceAgeOptions(ageMin)}</select></label>
      <label>Đến<select data-preset-field="Tuổi max">${audienceAgeOptions(ageMax)}</select></label>
      <div class="audience-gender wide"><span>Giới tính</span><input type="hidden" data-preset-field="Giới tính" value="${escapeHtml(gender)}"><div class="segmented-control" role="group" aria-label="Giới tính gợi ý">${['Tất cả','Nữ','Nam'].map(item=>`<button type="button" data-audience-gender="${item}" class="${gender===item?'selected':''}">${item}</button>`).join('')}</div></div>
      <label class="wide">Nhắm mục tiêu chi tiết <small>Không bắt buộc · có thể để trống khi chạy tệp rộng</small><input data-preset-field="Nhắm mục tiêu chi tiết" value="${escapeHtml(detail)}" list="detailedTargetingSuggestions" placeholder="Để trống hoặc chọn/tìm sở thích"><datalist id="detailedTargetingSuggestions"><option value="Chăm sóc da"><option value="Mỹ phẩm"><option value="Spa"><option value="Làm đẹp"><option value="Điều trị mụn"></datalist></label>
    </div>
  </section>
</div>`;}
function renderPresetList(){const list=$('presetList');$('libraryCount').textContent=`${state.presets.length} bundle đã lưu`;list.className=`preset-list${state.presets.length?'':' empty-state'}`;list.innerHTML=state.presets.length?state.presets.map(item=>`<button type="button" class="preset-card ${state.editingPresetCode===item.code?'selected':''}" data-preset-code="${escapeHtml(item.code)}"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.code)}</small></span><em>${escapeHtml(item.summary||'Chưa có mô tả')}</em></button>`).join(''):'Chưa có bundle. Hãy tạo bundle đầu tiên.';}
function openPresetForm(preset=null){const meta=PRESET_META[state.appView],isAudience=state.appView==='audiences';state.editingPresetCode=preset?.code||null;$('emptyPresetEditor').classList.add('hidden');$('presetForm').classList.remove('hidden');$('presetForm').classList.toggle('audience-preset-form',isAudience);$('presetFormTitle').textContent=preset?'Chỉnh sửa bundle':isAudience?'Tạo tệp đối tượng':'Tạo bundle mới';$('presetCodeField').classList.toggle('hidden',isAudience);$('presetCode').value=preset?.code||(isAudience?`AUD_${Date.now().toString(36).toUpperCase()}`:meta.prefix);$('presetCode').readOnly=Boolean(preset);$('presetName').value=preset?.name||(isAudience?'Tệp rộng Phan Thiết':'');$('presetSummary').value=preset?.summary||(isAudience?'Kiểm soát tại Phan Thiết; phần gợi ý có thể để rộng.':'');$('presetFields').classList.toggle('audience-preset-fields',isAudience);$('presetFields').innerHTML=isAudience?audienceFieldsHtml(preset):meta.fields.map(presetFieldHtml).join('');if(!isAudience)meta.fields.forEach(([key,,type])=>{const input=document.querySelector(`[data-preset-field="${CSS.escape(key)}"]`);const value=preset?.notionValues?.[key];input.value=value??'';if(type==='number'&&value===0)input.value='0';});renderPresetList();$('presetName').focus();}
function closePresetForm(){$('presetForm').classList.add('hidden');$('emptyPresetEditor').classList.remove('hidden');state.editingPresetCode=null;renderPresetList();}
async function loadPresetLibrary(kind){const result=await api(`/api/presets/${kind}`);state.presets=result.presets;renderPresetList();}
async function showAppView(kind){state.appView=kind;document.querySelectorAll('[data-app-view]').forEach(button=>button.classList.toggle('active',button.dataset.appView===kind));$('exportView').classList.add('hidden');const planner=kind==='planner',reviews=kind==='reviews',library=!planner&&!reviews;$('plannerWorkspace').classList.toggle('hidden',!planner);$('plannerActionbar').classList.toggle('hidden',!planner);$('libraryView').classList.toggle('hidden',!library);$('reviewView').classList.toggle('hidden',!reviews);$('reviewExportButton').classList.toggle('hidden',!planner);$('resetButton').classList.toggle('hidden',!planner);$('backToPlannerButton').classList.add('hidden');if(planner){$('pageTitle').textContent='Lập kế hoạch quảng cáo';$('pageSubtitle').textContent='Content chuẩn bị kế hoạch và gửi IT/Ads Operator kiểm tra.';return;}if(reviews){$('pageTitle').textContent='Duyệt kế hoạch quảng cáo';$('pageSubtitle').textContent='Kiểm tra cây Campaign → Nhóm quảng cáo → Quảng cáo trước khi tạo PAUSED trên Meta.';await Promise.all([loadAuth(),loadReviews()]);return;}const meta=PRESET_META[kind];$('pageTitle').textContent=meta.title;$('pageSubtitle').textContent=meta.subtitle;$('libraryTitle').textContent=meta.title;closePresetForm();try{await loadPresetLibrary(kind);}catch(error){showToast(error.message,true);}}
async function savePreset(event){event.preventDefault();const notionValues={};if(state.appView==='audiences'){const templateName=document.querySelector('[data-preset-field="Mẫu đối tượng"]');if(templateName)templateName.value=$('presetName').value.trim();}PRESET_META[state.appView].fields.forEach(([key,,type])=>{const input=document.querySelector(`[data-preset-field="${CSS.escape(key)}"]`);const raw=String(input?.value??'').trim();if(raw!=='')notionValues[key]=type==='number'?Number(raw):raw;});const payload={code:$('presetCode').value.trim().toUpperCase(),name:$('presetName').value.trim(),summary:$('presetSummary').value.trim(),notionValues};try{const path=state.editingPresetCode?`/api/presets/${state.appView}/${encodeURIComponent(state.editingPresetCode)}`:`/api/presets/${state.appView}`;await api(path,{method:state.editingPresetCode?'PUT':'POST',body:JSON.stringify(payload)});const catalog=await api('/api/planner/catalog');state.catalog=catalog.catalog;await loadPresetLibrary(state.appView);closePresetForm();showToast('Đã lưu bundle và cập nhật vào Planner.');}catch(error){showToast(error.message,true);}}

renderPlan=renderAssignedPlan;
function setAllPlanLinks(selected){state.selectedLinks=selected?links():[];saveLocalPlan();renderPlan();}
function updatePlanLinkSelection(event){const input=event.target.closest('[data-plan-link-index]');if(!input)return;const link=links()[Number(input.dataset.planLinkIndex)];if(!link)return;const selected=new Set(selectedLinks());if(input.checked)selected.add(link);else selected.delete(link);state.selectedLinks=links().filter(item=>selected.has(item));saveLocalPlan();renderPlan();}

document.addEventListener('click',e=>{const audienceGender=e.target.closest('[data-audience-gender]');if(audienceGender){const control=audienceGender.closest('.audience-gender');control.querySelector('[data-preset-field="Giới tính"]').value=audienceGender.dataset.audienceGender;control.querySelectorAll('[data-audience-gender]').forEach(button=>button.classList.toggle('selected',button===audienceGender));return;}const nav=e.target.closest('[data-app-view]');if(nav){showAppView(nav.dataset.appView);return;}const reviewCard=e.target.closest('[data-review-id]');if(reviewCard){selectReview(reviewCard.dataset.reviewId);return;}const reviewFilter=e.target.closest('[data-review-filter]');if(reviewFilter){state.reviewFilter=reviewFilter.dataset.reviewFilter;document.querySelectorAll('[data-review-filter]').forEach(button=>button.classList.toggle('active',button===reviewFilter));renderReviewList();return;}const presetButton=e.target.closest('[data-preset-code]');if(presetButton){openPresetForm(state.presets.find(item=>item.code===presetButton.dataset.presetCode));return;}const campaign=e.target.closest('[data-campaign]');if(campaign){state.campaign=campaign.dataset.campaign;state.location=null;state.adset=null;renderCampaigns();renderLocations();renderAdsets();return;}const location=e.target.closest('[data-location]');if(location){state.location=location.dataset.location;state.adset=null;renderLocations();renderAdsets();return;}const adset=e.target.closest('[data-adset]');if(adset){state.adset=adset.dataset.adset;renderAdsets();openSetup();return;}const edit=e.target.closest('[data-edit]');if(edit){editFlow(edit.dataset.edit);return;}const copy=e.target.closest('[data-copy]');if(copy)duplicateFlow(copy.dataset.copy);const del=e.target.closest('[data-delete]');if(del)removeFlow(del.dataset.delete);});
els.adName.addEventListener('input',()=>{saveLocalPlan();renderPlan();});els.budget.addEventListener('change',applyBudgetPreset);els.budgetType.addEventListener('change',toggleEndTime);els.hasEndTime.addEventListener('change',toggleEndTime);els.changeSelection.addEventListener('click',changeOrCancelSelection);$('addFlowButton').addEventListener('click',addFlow);$('resetButton').addEventListener('click',resetPlan);els.previewButton.addEventListener('click',preview);els.createButton.addEventListener('click',createDrafts);$('closeDialog').addEventListener('click',()=>$('previewDialog').close());
els.links.addEventListener('input',()=>{syncLinkSelection();saveLocalPlan();renderPlan();scheduleCreativePreviews();});els.linkSelection.addEventListener('change',updatePlanLinkSelection);$('selectAllLinksButton').addEventListener('click',()=>setAllPlanLinks(true));$('clearLinkSelectionButton').addEventListener('click',()=>setAllPlanLinks(false));
$('reviewExportButton').addEventListener('click',showExportView);$('backToPlannerButton').addEventListener('click',showPlannerView);$('refreshCandidatesButton').addEventListener('click',loadCandidates);$('exportSelectedButton').addEventListener('click',exportSelected);$('candidateList').addEventListener('change',updateExportSelection);$('selectAllCandidates').addEventListener('change',event=>{document.querySelectorAll('[data-candidate-id]').forEach(input=>{input.checked=event.target.checked;});updateExportSelection();});
$('newPresetButton').addEventListener('click',()=>openPresetForm());$('cancelPresetButton').addEventListener('click',closePresetForm);$('presetForm').addEventListener('submit',savePreset);
$('refreshReviewsButton').addEventListener('click',loadReviews);$('approverLoginButton').addEventListener('click',()=>$('approverDialog').showModal());$('closeApproverDialog').addEventListener('click',closeApproverDialog);$('approverDialog').addEventListener('cancel',()=>{$('approverKey').value='';});$('approverDialog').addEventListener('click',event=>{if(event.target!==event.currentTarget)return;const box=event.currentTarget.getBoundingClientRect();const inside=event.clientX>=box.left&&event.clientX<=box.right&&event.clientY>=box.top&&event.clientY<=box.bottom;if(!inside)closeApproverDialog();});$('approverLogoutButton').addEventListener('click',logoutApprover);$('approverForm').addEventListener('submit',loginApprover);$('approveReviewButton').addEventListener('click',()=>reviewAction('approve'));$('rejectReviewButton').addEventListener('click',()=>reviewAction('reject'));$('publishReviewButton').addEventListener('click',()=>reviewAction('publish'));

async function start(){try{const [health,data,configuredMeta]=await Promise.all([api('/api/health'),api('/api/planner/catalog'),api('/api/meta/status')]);state.catalog=data.catalog;let meta=configuredMeta;if(meta.configured){try{meta=await api('/api/meta/status?verify=true');}catch(_error){}}const currency=String(meta.account?.currency||'').toUpperCase();if(currency){state.metaCurrency=currency;els.budgetCurrency.textContent=currency;els.budgetAmount.placeholder=currency==='VND'?'Ví dụ: 200000':'Ví dụ: 10';$('budgetHelp').textContent=`Tiền tệ cố định của tài khoản quảng cáo: ${currency}; Meta không tự quy đổi`;}$('serverDot').classList.add('ok');$('serverText').textContent=meta.configured?'Backend + Meta đã cấu hình':'Backend đang chạy · Meta chưa cấu hình';const restored=restoreLocalPlan();renderCampaigns();renderLocations();renderAdsets();renderPlan();if(links().length)scheduleCreativePreviews();if(restored)showToast('Đã khôi phục kế hoạch đang làm.');}catch(e){$('serverText').textContent='Không kết nối được backend';showToast(e.message,true);}}
start();
