const state={catalog:null,flows:[],campaign:null,location:null,adset:null,preview:null,previewPayload:null,editingFlowId:null,candidates:[],appView:'planner',editingPresetCode:null,presets:[]};
const $=id=>document.getElementById(id);
const LOCAL_PLAN_KEY='khai_hoan_ads_plan_v1';
const els={links:$('linksInput'),adName:$('adNameInput'),campaigns:$('campaignList'),locations:$('locationList'),adsets:$('adsetList'),selection:$('selectionStage'),setup:$('setupStage'),path:$('selectedPath'),changeSelection:$('changeSelection'),audience:$('audienceSelect'),dataset:$('datasetSelect'),datasetHint:$('datasetHint'),budget:$('budgetSelect'),placement:$('placementSelect'),budgetType:$('budgetType'),budgetAmount:$('budgetAmount'),startTime:$('startTime'),hasEndTime:$('hasEndTime'),endTimeField:$('endTimeField'),endTime:$('endTime'),flows:$('flowList'),articles:$('articleList'),summary:$('summaryText'),readiness:$('readiness'),actionSummary:$('actionSummary'),actionHint:$('actionHint'),previewButton:$('previewButton'),createButton:$('createDraftsButton')};

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function links(){return [...new Set(els.links.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];}
function isFacebookLink(link){try{const host=new URL(link).hostname.toLowerCase();return host==='facebook.com'||host.endsWith('.facebook.com')||host==='fb.watch'||host.endsWith('.fb.watch');}catch(_error){return false;}}
function byCode(items,code){return items.find(item=>item.code===code);}
function optionList(select,items,emptyLabel){select.innerHTML=`<option value="">${escapeHtml(emptyLabel)}</option>`+items.map(x=>`<option value="${escapeHtml(x.code)}">${escapeHtml(x.name)}</option>`).join('');}
function defaultLocalDateTime(){const date=new Date();date.setSeconds(0,0);date.setMinutes(Math.ceil(date.getMinutes()/5)*5);const pad=value=>String(value).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function applyBudgetPreset(){const preset=byCode(state.catalog.budgets,els.budget.value);if(!preset)return;const values=preset.notionValues||{};const lifetime=values['Loại ngân sách']==='Lifetime'||Number(values['Ngân sách trọn đời'])>0;els.budgetType.value=lifetime?'Ngân sách trọn đời':'Ngân sách/ngày';const amount=lifetime?values['Ngân sách trọn đời']:values['Ngân sách/ngày'];if(amount!==undefined&&amount!==null&&amount!=='')els.budgetAmount.value=amount;}
function toggleEndTime(){const required=els.budgetType.value==='Ngân sách trọn đời';if(required)els.hasEndTime.checked=true;els.hasEndTime.disabled=required;els.endTimeField.classList.toggle('hidden',!els.hasEndTime.checked);if(!els.hasEndTime.checked)els.endTime.value='';}
function budgetSummary(flow){const custom=flow.custom_budget_values||{};const lifetime=custom['Ngân sách trọn đời']!==undefined;const amount=lifetime?custom['Ngân sách trọn đời']:custom['Ngân sách/ngày'];if(amount!==undefined)return `${amount} · ${lifetime?'Trọn đời':'Mỗi ngày'} (theo tiền tệ TKQC)`;return byCode(state.catalog.budgets,flow.budget_code)?.name||'Chưa chọn ngân sách';}
function scheduleSummary(flow){const format=value=>value?new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Không giới hạn';return `${format(flow.start_time)} → ${format(flow.end_time)}`;}
function showToast(message,error=false){const toast=$('toast');toast.textContent=message;toast.className=`toast${error?' error':''}`;setTimeout(()=>toast.classList.add('hidden'),3500);}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Máy chủ không phản hồi');return data;}
function saveLocalPlan(){try{localStorage.setItem(LOCAL_PLAN_KEY,JSON.stringify({version:1,links:els.links.value,adName:els.adName.value,flows:state.flows}));}catch(_error){}}
function restoreLocalPlan(){try{const saved=JSON.parse(localStorage.getItem(LOCAL_PLAN_KEY)||'null');if(!saved||saved.version!==1)return false;const campaigns=new Set(state.catalog.campaigns.map(x=>x.code));const adsets=new Map(state.catalog.adsets.map(x=>[x.code,x]));state.flows=(saved.flows||[]).filter(flow=>campaigns.has(flow.campaign_code)&&adsets.get(flow.adset_code)?.campaignBundleCode===flow.campaign_code).map(flow=>({...flow,id:flow.id||crypto.randomUUID(),start_time:flow.start_time||defaultLocalDateTime(),end_time:flow.end_time||null}));els.links.value=String(saved.links||'');els.adName.value=String(saved.adName||'');return Boolean(state.flows.length||els.links.value.trim());}catch(_error){return false;}}

function renderCampaigns(){els.campaigns.innerHTML=state.catalog.campaigns.map(c=>`<button class="choice ${state.campaign===c.code?'selected':''}" data-campaign="${c.code}"><strong>${escapeHtml(c.objectiveName||c.name)}</strong><small>${escapeHtml(c.description||'')}</small></button>`).join('');}
function renderLocations(){if(!state.campaign){els.locations.className='location-list empty-state';els.locations.textContent='Chọn chiến dịch trước';return;}const groups=[...new Set(state.catalog.adsets.filter(a=>a.campaignBundleCode===state.campaign).map(a=>a.conversionLocation))];els.locations.className='location-list';els.locations.innerHTML=groups.map(name=>`<button class="location-chip ${state.location===name?'selected':''}" data-location="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join('');}
function renderAdsets(){if(!state.location){els.adsets.className='choice-list adset-list empty-state';els.adsets.textContent='Chọn vị trí chuyển đổi';return;}const items=state.catalog.adsets.filter(a=>a.campaignBundleCode===state.campaign&&a.conversionLocation===state.location);els.adsets.className='choice-list adset-list';els.adsets.innerHTML=items.map(a=>`<button class="choice ${state.adset===a.code?'selected':''}" data-adset="${a.code}"><strong>${escapeHtml(a.performanceGoal||a.name)}</strong><small>${escapeHtml(a.summary||'')}</small></button>`).join('');}
function allowedAudiences(){const campaign=byCode(state.catalog.campaigns,state.campaign);const allowed=new Set(campaign?.allowedAudiencePresetCodes||[]);return state.catalog.audiences.filter(x=>!allowed.size||allowed.has(x.code));}
function openSetup(){const campaign=byCode(state.catalog.campaigns,state.campaign);const adset=byCode(state.catalog.adsets,state.adset);if(!campaign||!adset)return;els.selection.classList.add('hidden');els.setup.classList.remove('hidden');els.path.textContent='';const strong=document.createElement('strong');strong.textContent=`${campaign.objectiveName||campaign.name} → ${adset.conversionLocation} → ${adset.performanceGoal}`;els.path.append(strong,els.changeSelection);optionList(els.audience,allowedAudiences(),'Chọn nhóm người xem bắt buộc');const datasets=adset.requiresDataset?state.catalog.datasets.filter(item=>item.code!=='DATASET_NONE'):state.catalog.datasets;optionList(els.dataset,datasets,adset.requiresDataset?'Chọn nguồn dữ liệu bắt buộc':'Không chọn nguồn dữ liệu');els.datasetHint.textContent=adset.requiresDataset?'Bắt buộc':'';optionList(els.budget,state.catalog.budgets,'Chọn mức thường dùng');optionList(els.placement,state.catalog.placements,'Không chọn vị trí hiển thị');if(adset.requiresDataset&&datasets[0])els.dataset.value=datasets[0].code;else if(state.catalog.datasets[0])els.dataset.value=state.catalog.datasets[0].code;if(state.catalog.budgets[0]){els.budget.value=state.catalog.budgets[0].code;applyBudgetPreset();}if(state.catalog.placements[0])els.placement.value=state.catalog.placements[0].code;els.startTime.value=defaultLocalDateTime();els.hasEndTime.checked=false;els.endTime.value='';toggleEndTime();}
function closeSetup(){els.setup.classList.add('hidden');els.selection.classList.remove('hidden');}
function resetDraft(){state.location=null;state.adset=null;state.editingFlowId=null;$('addFlowButton').textContent='+ Thêm cách chạy vào kế hoạch';els.changeSelection.textContent='Đổi lựa chọn';els.budgetAmount.value='';els.startTime.value='';els.hasEndTime.checked=false;els.hasEndTime.disabled=false;els.endTime.value='';toggleEndTime();renderLocations();renderAdsets();closeSetup();}
function flowLabel(flow){const c=byCode(state.catalog.campaigns,flow.campaign_code);const a=byCode(state.catalog.adsets,flow.adset_code);return `${c?.objectiveName||c?.name||''} → ${a?.conversionLocation||''} → ${a?.performanceGoal||''}`;}
function addFlow(){const adset=byCode(state.catalog.adsets,state.adset);if(!adset)return;if(!els.audience.value){showToast('Hãy chọn một nhóm người xem cho cách chạy này.',true);els.audience.focus();return;}if(adset.requiresDataset&&(!els.dataset.value||els.dataset.value==='DATASET_NONE')){showToast('Nhóm quảng cáo này bắt buộc chọn nguồn dữ liệu.',true);els.dataset.focus();return;}const custom={};const rawAmount=els.budgetAmount.value.trim();const normalizedAmount=rawAmount.replace(',','.');if(!rawAmount||!/^\d+(?:[.,]\d+)?$/.test(rawAmount)||Number(normalizedAmount)<=0){showToast('Số tiền tùy chỉnh phải là một số lớn hơn 0.',true);els.budgetAmount.focus();return;}if(!els.startTime.value){showToast('Hãy chọn thời gian bắt đầu.',true);els.startTime.focus();return;}if(els.budgetType.value==='Ngân sách trọn đời'&&!els.endTime.value){showToast('Ngân sách trọn đời bắt buộc phải có thời gian kết thúc.',true);els.endTime.focus();return;}if(els.endTime.value&&new Date(els.endTime.value)<=new Date(els.startTime.value)){showToast('Thời gian kết thúc phải sau thời gian bắt đầu.',true);els.endTime.focus();return;}custom[els.budgetType.value]=normalizedAmount;const flow={id:state.editingFlowId||crypto.randomUUID(),campaign_code:state.campaign,adset_code:state.adset,audience_codes:[els.audience.value],dataset_code:els.dataset.value||null,budget_code:els.budget.value||null,custom_budget_values:custom,start_time:els.startTime.value,end_time:els.hasEndTime.checked?els.endTime.value:null,placement_code:els.placement.value||null,creative_mode:'existing_post'};if(state.editingFlowId){const index=state.flows.findIndex(item=>item.id===state.editingFlowId);if(index>=0)state.flows[index]=flow;showToast('Đã cập nhật cách chạy.');}else{state.flows.push(flow);}resetDraft();saveLocalPlan();renderPlan();}
function editFlow(id){const flow=state.flows.find(item=>item.id===id);if(!flow)return;const adset=byCode(state.catalog.adsets,flow.adset_code);if(!adset)return;state.editingFlowId=id;state.campaign=flow.campaign_code;state.location=adset.conversionLocation;state.adset=flow.adset_code;renderCampaigns();renderLocations();renderAdsets();openSetup();els.changeSelection.textContent='Hủy chỉnh sửa';els.audience.value=flow.audience_codes?.[0]||'';els.dataset.value=flow.dataset_code||'';els.budget.value=flow.budget_code||'';els.placement.value=flow.placement_code||'';const custom=flow.custom_budget_values||{};if(custom['Ngân sách trọn đời']!==undefined){els.budgetType.value='Ngân sách trọn đời';els.budgetAmount.value=custom['Ngân sách trọn đời'];}else{els.budgetType.value='Ngân sách/ngày';els.budgetAmount.value=custom['Ngân sách/ngày']??'';}els.startTime.value=(flow.start_time||defaultLocalDateTime()).slice(0,16);els.hasEndTime.checked=Boolean(flow.end_time);els.endTime.value=(flow.end_time||'').slice(0,16);toggleEndTime();$('addFlowButton').textContent='Lưu thay đổi cách chạy';}
function changeOrCancelSelection(){if(state.editingFlowId){resetDraft();showToast('Đã hủy chỉnh sửa, cách chạy cũ được giữ nguyên.');return;}closeSetup();}
function duplicateFlow(id){const source=state.flows.find(f=>f.id===id);if(source)state.flows.push({...structuredClone(source),id:crypto.randomUUID()});saveLocalPlan();renderPlan();}
function removeFlow(id){state.flows=state.flows.filter(f=>f.id!==id);if(state.editingFlowId===id)resetDraft();saveLocalPlan();renderPlan();}
function renderFlows(){if(!state.flows.length){els.flows.className='flow-list empty-state';els.flows.textContent='Chưa có cách chạy';return;}els.flows.className='flow-list';els.flows.innerHTML=state.flows.map((flow,i)=>{const audience=byCode(state.catalog.audiences,flow.audience_codes?.[0]);const dataset=byCode(state.catalog.datasets,flow.dataset_code);const placement=byCode(state.catalog.placements,flow.placement_code);return `<div class="flow-card"><div class="flow-main"><strong title="${escapeHtml(flowLabel(flow))}">${i+1}. ${escapeHtml(flowLabel(flow))}</strong><div class="flow-meta">${audience?`<span class="tag purple">${escapeHtml(audience.name)}</span>`:''}<span class="tag orange">${escapeHtml(budgetSummary(flow))}</span><span class="tag">${escapeHtml(scheduleSummary(flow))}</span>${dataset&&dataset.code!=='DATASET_NONE'?`<span class="tag">${escapeHtml(dataset.name)}</span>`:''}${placement?`<span class="tag green">${escapeHtml(placement.name)}</span>`:''}</div></div><button class="icon-button" data-edit="${flow.id}">Sửa</button><button class="icon-button" data-copy="${flow.id}">Chép</button><button class="icon-button danger" data-delete="${flow.id}">Xóa</button></div>`;}).join('');}
function renderArticles(){const currentLinks=links();if(!currentLinks.length){els.articles.className='article-list empty-state';els.articles.textContent='Dán đường dẫn bài viết để bắt đầu';return;}els.articles.className='article-list';els.articles.innerHTML=currentLinks.map((link,i)=>{const valid=isFacebookLink(link);const flowGroups=state.flows.map((flow,flowIndex)=>{const adset=byCode(state.catalog.adsets,flow.adset_code);const audience=byCode(state.catalog.audiences,flow.audience_codes[0]);const dataset=byCode(state.catalog.datasets,flow.dataset_code);const placement=byCode(state.catalog.placements,flow.placement_code);return `<div class="article-flow"><b>Cách chạy ${flowIndex+1}</b><div class="tags"><span class="tag">${escapeHtml(adset?.conversionLocation||'')}</span><span class="tag green">${escapeHtml(adset?.performanceGoal||'')}</span>${audience?`<span class="tag purple">${escapeHtml(audience.name)}</span>`:''}<span class="tag orange">${escapeHtml(budgetSummary(flow))}</span><span class="tag">${escapeHtml(scheduleSummary(flow))}</span>${dataset?`<span class="tag">${escapeHtml(dataset.name)}</span>`:''}${placement?`<span class="tag">${escapeHtml(placement.name)}</span>`:''}</div></div>`;}).join('');return `<article class="article-card ${valid?'':'invalid-link'}"><div class="article-head"><strong>Bài ${i+1} · ${valid?'Hợp lệ':'Link không hợp lệ'}</strong><span title="${escapeHtml(link)}">${escapeHtml(link)}</span></div>${flowGroups||'<span class="empty-state">Chưa gán cách chạy</span>'}</article>`;}).join('');}
function renderPlan(){const currentLinks=links(),count=currentLinks.length,invalid=currentLinks.filter(link=>!isFacebookLink(link)).length,total=count*state.flows.reduce((n,f)=>n+Math.max(1,f.audience_codes.length),0),ready=count>0&&state.flows.length>0&&invalid===0,missing=Number(count===0)+Number(state.flows.length===0)+Number(invalid>0);$('linkCount').textContent=count?`${count} bài viết${invalid?` · ${invalid} link không hợp lệ`:''}`:'Chưa có bài viết';$('linkCount').classList.toggle('error-text',invalid>0);els.summary.textContent=`${count} bài · ${state.flows.length} cách chạy · ${total} mục`;els.readiness.textContent=ready?'Sẵn sàng tạo bản nháp':invalid?`Có ${invalid} đường dẫn không hợp lệ`:`Còn thiếu ${missing} mục`;els.readiness.classList.toggle('ready',ready);els.actionSummary.textContent=ready?`${total} mục sẽ được tạo`:'Chưa đủ dữ liệu';els.actionHint.textContent=ready?`${count} bài viết × ${state.flows.length} cách chạy`:invalid?'Sửa đường dẫn được đánh dấu lỗi':'Thêm bài viết và ít nhất một cách chạy';els.previewButton.disabled=!ready;els.createButton.disabled=!ready;renderFlows();renderArticles();}
function payload(){return{links:links(),flows:state.flows.map(({id,...flow})=>flow),ad_name:els.adName.value.trim()};}
function showExportView(){
  $('plannerWorkspace').classList.add('hidden');$('plannerActionbar').classList.add('hidden');$('exportView').classList.remove('hidden');$('reviewExportButton').classList.add('hidden');$('resetButton').classList.add('hidden');$('backToPlannerButton').classList.remove('hidden');document.querySelector('.page-heading h1').textContent='Duyệt và xuất CSV Meta';document.querySelector('.page-heading p').textContent='Chọn đúng các bài đã duyệt trên Notion để xuất.';loadCandidates();
}
function showPlannerView(){
  $('exportView').classList.add('hidden');$('plannerWorkspace').classList.remove('hidden');$('plannerActionbar').classList.remove('hidden');$('reviewExportButton').classList.remove('hidden');$('resetButton').classList.remove('hidden');$('backToPlannerButton').classList.add('hidden');document.querySelector('.page-heading h1').textContent='Lập kế hoạch quảng cáo';document.querySelector('.page-heading p').textContent='Thêm bài viết và cấu hình từng cách chạy trong một màn hình.';
}
function selectedCandidateIds(){return [...document.querySelectorAll('[data-candidate-id]:checked')].map(input=>input.dataset.candidateId);}
function updateExportSelection(){const selected=selectedCandidateIds().length;$('exportSelectedButton').disabled=selected===0;$('exportSelectedButton').textContent=selected?`Xuất ${selected} bài đã chọn`:'Xuất các bài đã chọn';$('selectAllCandidates').checked=Boolean(state.candidates.length&&selected===state.candidates.length);}
function renderCandidates(){const host=$('candidateList');$('candidateCount').textContent=`${state.candidates.length} bài đủ điều kiện`;if(!state.candidates.length){host.className='candidate-list empty-state';host.textContent='Không có bài Hoàn thành nào đang chờ xuất.';updateExportSelection();return;}host.className='candidate-list';host.innerHTML=state.candidates.map(item=>`<article class="candidate-card"><input type="checkbox" data-candidate-id="${escapeHtml(item.id)}"><div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.campaign)} · ${escapeHtml(item.adset)}</p><p>${escapeHtml(item.audience)}${item.budget?` · Ngân sách ${escapeHtml(item.budget)}`:''}</p><p title="${escapeHtml(item.post_url)}">${escapeHtml(item.post_url)}</p><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">Mở Notion</a></div><span class="candidate-status">${escapeHtml(item.status)}</span></article>`).join('');updateExportSelection();}
async function loadCandidates(){const host=$('candidateList');host.className='candidate-list empty-state';host.textContent='Đang đọc bài đã duyệt từ Notion…';$('refreshCandidatesButton').disabled=true;$('exportResult').classList.add('hidden');try{const data=await api('/api/export/candidates');state.candidates=data.candidates||[];renderCandidates();}catch(error){host.textContent=error.message;showToast(error.message,true);}finally{$('refreshCandidatesButton').disabled=false;}}
async function exportSelected(){const pageIds=selectedCandidateIds();if(!pageIds.length)return;if(!confirm(`Xuất ${pageIds.length} bài đã chọn và đánh dấu đã xuất trên Notion?`))return;const button=$('exportSelectedButton');button.disabled=true;button.textContent='Đang tạo CSV Meta…';try{const data=await api('/api/export',{method:'POST',body:JSON.stringify({page_ids:pageIds})});const result=$('exportResult');result.innerHTML=`Đã xuất <strong>${data.count}</strong> quảng cáo. <a href="${escapeHtml(data.download_url)}">Tải file ${escapeHtml(data.file_name)}</a>${data.sync_warning?`<br><small>Cảnh báo đồng bộ: ${escapeHtml(data.sync_warning)}</small>`:''}`;result.classList.remove('hidden');await loadCandidates();result.classList.remove('hidden');}catch(error){showToast(error.message,true);}finally{button.textContent='Xuất các bài đã chọn';updateExportSelection();}}
async function preview(){els.previewButton.disabled=true;els.previewButton.textContent='Đang kiểm tra Meta…';try{const requestPayload=payload();const data=await api('/api/meta/preview',{method:'POST',body:JSON.stringify(requestPayload)});state.preview=data.plan;state.previewPayload=JSON.stringify(requestPayload);const p=data.plan;const account=p.account;$('previewContent').innerHTML=`<p><strong>${p.summary.campaigns_count}</strong> campaign · <strong>${p.summary.adsets_count}</strong> ad set · <strong>${p.summary.ads_count}</strong> ads</p><p>Tài khoản: <strong>${escapeHtml(account.name||account.id)}</strong> · ${escapeHtml(account.currency)} · ${escapeHtml(account.timezone_name)}<br><small>Tất cả campaign, ad set và ads đều được tạo ở trạng thái PAUSED.</small></p>`+p.flows.map((f,i)=>`<div class="preview-row"><strong>${i+1}. ${escapeHtml(f.campaign_name)}</strong><br>${escapeHtml(f.adset_name)}<br><small>${escapeHtml(f.budget_major)} ${escapeHtml(f.currency)} · ${escapeHtml(f.start_time||'Chưa đặt lịch')} → ${escapeHtml(f.end_time||'Không giới hạn')}</small><br><small>Mẫu Meta: ${escapeHtml(f.source_adset_id)}</small></div>`).join('');$('previewDialog').showModal();}catch(e){state.preview=null;state.previewPayload=null;showToast(e.message,true);}finally{els.previewButton.textContent='Xem trước';renderPlan();}}
async function createDrafts(){const requestPayload=payload();if(!state.preview||state.previewPayload!==JSON.stringify(requestPayload)){showToast('Kế hoạch đã thay đổi hoặc chưa được kiểm tra. Hãy bấm Xem trước lại.',true);return;}if(!confirm(`Tạo ${state.preview.summary.ads_count} ads trên Meta ở trạng thái PAUSED?`))return;const expected=state.preview.summary.ads_count;els.createButton.disabled=true;els.createButton.textContent=`Đang tạo ${expected} ads PAUSED…`;try{const data=await api('/api/meta/drafts',{method:'POST',body:JSON.stringify(requestPayload)});const parts=[data.status==='skipped'?'Kế hoạch đã tồn tại':`Đã tạo ${data.created} ads PAUSED`];if(data.skipped)parts.push(`bỏ qua ${data.skipped} ads đã có`);showToast(parts.join(' · '));const details=Object.entries(data.objects||{}).map(([position,item])=>`<div class="preview-row"><strong>Cách chạy ${escapeHtml(position)}</strong><br>Campaign: ${escapeHtml(item.campaign_id)}<br>Ad set: ${escapeHtml(item.adset_id)}<br><small>${Object.values(item.ads||{}).map(ad=>`Ad ${escapeHtml(ad.ad_id)} · Creative ${escapeHtml(ad.creative_id)}`).join('<br>')}</small></div>`).join('');$('previewContent').innerHTML=`<p><strong>${data.created}</strong> ads đã tạo · <strong>${data.skipped}</strong> ads bỏ qua</p><p><small>Tất cả đối tượng vẫn PAUSED, chưa thể tiêu ngân sách.</small></p>${details}`;$('previewDialog').showModal();}catch(e){state.preview=null;state.previewPayload=null;showToast(e.message,true);}finally{els.createButton.textContent='Tạo bản nháp PAUSED trên Meta';renderPlan();}}
function resetPlan(){if(state.flows.length||links().length){if(!confirm('Xóa kế hoạch đang nhập để làm kế hoạch mới?'))return;}state.flows=[];state.campaign=null;state.location=null;state.adset=null;state.editingFlowId=null;els.links.value='';els.adName.value='';localStorage.removeItem(LOCAL_PLAN_KEY);closeSetup();renderCampaigns();renderLocations();renderAdsets();renderPlan();}

const PRESET_META={
  audiences:{title:'Tệp đối tượng',subtitle:'Tạo và lưu nhóm người xem trước khi đưa vào Planner.',prefix:'AUD_',fields:[['Mẫu đối tượng','Tên mẫu đối tượng'],['Đối tượng tuỳ chỉnh','Đối tượng tùy chỉnh'],['Vị trí địa lý','Vị trí địa lý'],['Tuổi min','Tuổi nhỏ nhất','number'],['Tuổi max','Tuổi lớn nhất','number'],['Giới tính','Giới tính'],['Ngôn ngữ','Ngôn ngữ'],['Thiết bị','Thiết bị']]},
  placements:{title:'Vị trí quảng cáo',subtitle:'Hoàn thiện bundle nơi hiển thị để Planner chỉ cần chọn.',prefix:'PLC_',fields:[['Nền tảng quảng cáo','Nền tảng quảng cáo'],['Vị trí Facebook','Vị trí trên Facebook'],['Vị trí Messenger','Vị trí trên Messenger'],['Thiết bị','Thiết bị'],['Mở rộng nhắm chọn','Mở rộng nhắm chọn']]},
  budgets:{title:'Ngân sách',subtitle:'Lưu các mức ngân sách thường dùng để áp dụng nhất quán.',prefix:'BUD_',fields:[['Loại ngân sách','Loại ngân sách','select',['Daily','Lifetime']],['Ngân sách/ngày','Ngân sách mỗi ngày','number'],['Ngân sách trọn đời','Ngân sách trọn đời','number'],['Tính phí theo','Cách tính phí']]}
};
function presetFieldHtml([key,label,type='text',options=[]]){const control=type==='select'?`<select data-preset-field="${escapeHtml(key)}">${options.map(item=>`<option value="${item}">${item}</option>`).join('')}</select>`:`<input data-preset-field="${escapeHtml(key)}" type="${type}" ${type==='number'?'min="0" step="any"':''}>`;return `<label>${escapeHtml(label)}${control}</label>`;}
function renderPresetList(){const list=$('presetList');$('libraryCount').textContent=`${state.presets.length} bundle đã lưu`;list.className=`preset-list${state.presets.length?'':' empty-state'}`;list.innerHTML=state.presets.length?state.presets.map(item=>`<button type="button" class="preset-card ${state.editingPresetCode===item.code?'selected':''}" data-preset-code="${escapeHtml(item.code)}"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.code)}</small></span><em>${escapeHtml(item.summary||'Chưa có mô tả')}</em></button>`).join(''):'Chưa có bundle. Hãy tạo bundle đầu tiên.';}
function openPresetForm(preset=null){const meta=PRESET_META[state.appView];state.editingPresetCode=preset?.code||null;$('emptyPresetEditor').classList.add('hidden');$('presetForm').classList.remove('hidden');$('presetFormTitle').textContent=preset?'Chỉnh sửa bundle':'Tạo bundle mới';$('presetCode').value=preset?.code||meta.prefix;$('presetCode').readOnly=Boolean(preset);$('presetName').value=preset?.name||'';$('presetSummary').value=preset?.summary||'';$('presetFields').innerHTML=meta.fields.map(presetFieldHtml).join('');meta.fields.forEach(([key,,type])=>{const input=document.querySelector(`[data-preset-field="${CSS.escape(key)}"]`);const value=preset?.notionValues?.[key];input.value=value??'';if(type==='number'&&value===0)input.value='0';});renderPresetList();$('presetName').focus();}
function closePresetForm(){$('presetForm').classList.add('hidden');$('emptyPresetEditor').classList.remove('hidden');state.editingPresetCode=null;renderPresetList();}
async function loadPresetLibrary(kind){const result=await api(`/api/presets/${kind}`);state.presets=result.presets;renderPresetList();}
async function showAppView(kind){state.appView=kind;document.querySelectorAll('[data-app-view]').forEach(button=>button.classList.toggle('active',button.dataset.appView===kind));$('exportView').classList.add('hidden');const planner=kind==='planner';$('plannerWorkspace').classList.toggle('hidden',!planner);$('plannerActionbar').classList.toggle('hidden',!planner);$('libraryView').classList.toggle('hidden',planner);$('reviewExportButton').classList.toggle('hidden',!planner);$('resetButton').classList.toggle('hidden',!planner);$('backToPlannerButton').classList.add('hidden');if(planner){$('pageTitle').textContent='Lập kế hoạch quảng cáo';$('pageSubtitle').textContent='Chọn các bundle đã hoàn thiện để tạo kế hoạch.';return;}const meta=PRESET_META[kind];$('pageTitle').textContent=meta.title;$('pageSubtitle').textContent=meta.subtitle;$('libraryTitle').textContent=meta.title;closePresetForm();try{await loadPresetLibrary(kind);}catch(error){showToast(error.message,true);}}
async function savePreset(event){event.preventDefault();const notionValues={};PRESET_META[state.appView].fields.forEach(([key,,type])=>{const raw=document.querySelector(`[data-preset-field="${CSS.escape(key)}"]`).value.trim();if(raw!=='')notionValues[key]=type==='number'?Number(raw):raw;});const payload={code:$('presetCode').value.trim().toUpperCase(),name:$('presetName').value.trim(),summary:$('presetSummary').value.trim(),notionValues};try{const path=state.editingPresetCode?`/api/presets/${state.appView}/${encodeURIComponent(state.editingPresetCode)}`:`/api/presets/${state.appView}`;await api(path,{method:state.editingPresetCode?'PUT':'POST',body:JSON.stringify(payload)});const catalog=await api('/api/planner/catalog');state.catalog=catalog.catalog;await loadPresetLibrary(state.appView);closePresetForm();showToast('Đã lưu bundle và cập nhật vào Planner.');}catch(error){showToast(error.message,true);}}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-app-view]');if(nav){showAppView(nav.dataset.appView);return;}const presetButton=e.target.closest('[data-preset-code]');if(presetButton){openPresetForm(state.presets.find(item=>item.code===presetButton.dataset.presetCode));return;}const campaign=e.target.closest('[data-campaign]');if(campaign){state.campaign=campaign.dataset.campaign;state.location=null;state.adset=null;renderCampaigns();renderLocations();renderAdsets();return;}const location=e.target.closest('[data-location]');if(location){state.location=location.dataset.location;state.adset=null;renderLocations();renderAdsets();return;}const adset=e.target.closest('[data-adset]');if(adset){state.adset=adset.dataset.adset;renderAdsets();openSetup();return;}const edit=e.target.closest('[data-edit]');if(edit){editFlow(edit.dataset.edit);return;}const copy=e.target.closest('[data-copy]');if(copy)duplicateFlow(copy.dataset.copy);const del=e.target.closest('[data-delete]');if(del)removeFlow(del.dataset.delete);});
els.links.addEventListener('input',()=>{saveLocalPlan();renderPlan();});els.adName.addEventListener('input',()=>{saveLocalPlan();renderPlan();});els.budget.addEventListener('change',applyBudgetPreset);els.budgetType.addEventListener('change',toggleEndTime);els.hasEndTime.addEventListener('change',toggleEndTime);els.changeSelection.addEventListener('click',changeOrCancelSelection);$('addFlowButton').addEventListener('click',addFlow);$('resetButton').addEventListener('click',resetPlan);els.previewButton.addEventListener('click',preview);els.createButton.addEventListener('click',createDrafts);$('closeDialog').addEventListener('click',()=>$('previewDialog').close());
$('reviewExportButton').addEventListener('click',showExportView);$('backToPlannerButton').addEventListener('click',showPlannerView);$('refreshCandidatesButton').addEventListener('click',loadCandidates);$('exportSelectedButton').addEventListener('click',exportSelected);$('candidateList').addEventListener('change',updateExportSelection);$('selectAllCandidates').addEventListener('change',event=>{document.querySelectorAll('[data-candidate-id]').forEach(input=>{input.checked=event.target.checked;});updateExportSelection();});
$('newPresetButton').addEventListener('click',()=>openPresetForm());$('cancelPresetButton').addEventListener('click',closePresetForm);$('presetForm').addEventListener('submit',savePreset);

async function start(){try{const [health,data,meta]=await Promise.all([api('/api/health'),api('/api/planner/catalog'),api('/api/meta/status')]);state.catalog=data.catalog;$('serverDot').classList.add('ok');$('serverText').textContent=meta.configured?'Backend + Meta đã cấu hình':'Backend đang chạy · Meta chưa cấu hình';const restored=restoreLocalPlan();renderCampaigns();renderLocations();renderAdsets();renderPlan();if(restored)showToast('Đã khôi phục kế hoạch đang làm.');}catch(e){$('serverText').textContent='Không kết nối được backend';showToast(e.message,true);}}
start();
